#!/bin/csh -f

# ****************************************************************
# *****                                                      *****
# *****  This script creates the necessary directories       *****
# *****  and file links for the STATS comparison table.      *****
# *****                                                      *****
# *****  Usage:  move_stats exp1[.exp2]                      *****
# *****                                                      *****
# *****  where:  exp1 is the directory name of the 1st exp   *****
# *****         [exp2 is the directory name of the 2nd exp]  *****
# *****                                                      *****
# ****************************************************************

if( -e $1 ) then
    cd $1
    mkdir -p ../../misc/stats
else
    echo Directory $1 does not exist
    exit
endif
               set MONTH0 = NULL
if( .$2 != . ) set MONTH0 = $2

set types  = `echo all syscmp`
set fields = `echo uwnd vwnd tmpu hght sphu chi psi`

foreach type ($types)

# Zonal Means
# -----------
set levels = `echo z zlog1 zlog10`

foreach level ($levels)
foreach field ($fields)
set files = `/bin/ls -1 | grep stats_${field}_${type}_GLO_z | grep -v "$MONTH0.gif"`
if( $#files > 0 ) then
     set node   = `echo $files[1] | cut -d. -f1`
       @ length = `echo $node | awk '{print length($0)}'` - 2
     if( $MONTH0 == NULL ) then
      set MONTH  = `echo $node | cut -c${length}-`
     else
      set MONTH = $MONTH0
     endif
     if(! -e    stats_${field}_${type}_GLO_${level}_$MONTH ) then
          mkdir stats_${field}_${type}_GLO_${level}_$MONTH
     endif
     set mvfiles = `/bin/ls -1 stats_${field}_${type}_GLO_${level}_$MONTH.*.gif`
     if( $#mvfiles != 0 ) then
       mv $mvfiles  stats_${field}_${type}_GLO_${level}_$MONTH
     endif

  if( -e    stats_${field}_${type}_GLO_${level}_${MONTH} ) then
         cd stats_${field}_${type}_GLO_${level}_${MONTH}
        /bin/ln -sf ../../../../pages/syscmp_index.php index.php
        cd ../
  endif
endif # End Files Test
end   # End Field Loop
end   # End Level Loop



# Horizontal Means
# ----------------
foreach field ($fields)

# Determine Levels for each Field
# --------------------------------
   set   files  = `/bin/ls -1 stats_${field}_${type}_GLO_*.1*.gif | grep -v GLO_z`
   set  levels  = `echo abcd | grep 1234`
   if( $#files != 0 ) then
    @ numlevs = 0
      foreach file ($files)
      set level  = `echo $file | cut -d_ -f5`
      if( $numlevs == 0 ) then
          set levels = "$levels $level"
          @ numlevs = $numlevs + 1
      else
          if( $level != $levels[$numlevs] ) then
               set levels = `echo $levels $level`
               @ numlevs = $numlevs + 1
          endif
      endif
      end
      echo Type: $type  Field: $field  Levels: $levels
   endif

if( $#levels > 0 ) then
foreach level ($levels)
set files = `/bin/ls -1 | grep stats_${field}_${type}_GLO_${level} | grep -v "$MONTH0.gif"`
if( $#files > 0 ) then
     set node   = `echo $files[1] | cut -d. -f1`
       @ length = `echo $node | awk '{print length($0)}'` - 2
     if( $MONTH0 == NULL ) then
      set MONTH  = `echo $node | cut -c${length}-`
     else
      set MONTH = $MONTH0
     endif
     if(! -e    stats_${field}_${type}_GLO_${level}_$MONTH ) then
          mkdir stats_${field}_${type}_GLO_${level}_$MONTH
     endif
     set mvfiles = `/bin/ls -1 stats_${field}_${type}_GLO_${level}_$MONTH.*.gif`
     if( $#mvfiles != 0 ) then
       mv $mvfiles  stats_${field}_${type}_GLO_${level}_$MONTH
     endif

  if( -e    stats_${field}_${type}_GLO_${level}_${MONTH} ) then
         cd stats_${field}_${type}_GLO_${level}_${MONTH}
        /bin/ln -sf ../../../../pages/syscmp_index.php index.php
        cd ../
  endif
endif # End Files Test
end   # End Level Loop
endif # End Level Test
end   # End Field Loop


# Sea Level Pressure
# ------------------
set level = `echo 1000`
set field = `echo slp`

set files = `/bin/ls -1 | grep stats_${field}_${type}_GLO_${level} | grep -v "$MONTH0.gif"`
if( $#files > 0 ) then
     set node   = `echo $files[1] | cut -d. -f1`
       @ length = `echo $node | awk '{print length($0)}'` - 2
     if( $MONTH0 == NULL ) then
      set MONTH  = `echo $node | cut -c${length}-`
     else
      set MONTH = $MONTH0
     endif
     if(! -e                       stats_${field}_${type}_GLO_${level}_$MONTH ) then
          mkdir                    stats_${field}_${type}_GLO_${level}_$MONTH
     endif
     set mvfiles = `/bin/ls -1 stats_${field}_${type}_GLO_${level}_$MONTH.*.gif`
     if( $#mvfiles != 0 ) then
       mv $mvfiles stats_${field}_${type}_GLO_${level}_$MONTH
     endif

  if( -e    stats_${field}_${type}_GLO_${level}_${MONTH} ) then
         cd stats_${field}_${type}_GLO_${level}_${MONTH}
        /bin/ln -sf ../../../../pages/syscmp_index.php index.php
        cd ../
  endif
endif # End Files Test

# --------------------------------------

end   # End Types Loop
