#!/bin/csh

echo
echo ' -------------------------------------------------------------------------------'
echo '                          NASA/GMAO GEOS GCM                                    '
echo '                           Recover Utility                                      '
echo ' -------------------------------------------------------------------------------'
echo

if ( ! $?CVSROOT | ! $?CVS_RSH ) then
      echo " "
      echo "Environment variables CVSROOT and CVS_RSH must be defined before use!"
      echo " "
      echo "  setenv CVS_RSH ssh"
      echo "  setenv CVSROOT :ext:USRID@c-sourcemotel.gsfc.nasa.gov:/cvsroot/esma"
      echo " "
      echo "  where USRID is your USRID on sourcemotel.gsfc.nasa.gov"
      exit 1
endif
                                                                                                                            
# Set USRID and ARCHIVE Director
# ------------------------------
set usrid   = $LOGNAME
set archive = /output/$usrid/GEOS5.0/intranet

echo "Enter USRID on server ALTA:  (Default = "${usrid}")"
set input = `line`
if( .$input != "." ) set usrid   = $input
echo "Enter ARCHIVE directory:  (Default = "${archive}")"
set input = `line`
if( .$input != "." ) set archive = $input
echo
 
foreach exp ($argv)
echo "Recovering Experiment: "$exp
echo
scp -r $archive/$exp $usrid@alta:/gmao/intranet/research/modeling/agcm/geos5
set rc_recover = $status

if( $rc_recover == 0 ) then

/bin/mv current_list current.tmp
if( -e sedfile  ) /bin/rm  sedfile
cat >  sedfile << EOF
s?zref=$exp?href=$exp?g
s?!-- $exp?a-- $exp?g
s?$exp !--?$exp a--?g
EOF
sed -f sedfile current.tmp > current_list

/bin/mv archive_list archive.tmp
if( -e sedfile  ) /bin/rm  sedfile
cat >  sedfile << EOF
s?zref=$exp?href=$exp?g
EOF
sed -f sedfile archive.tmp > archive_list

cvs commit -m "Recover Experiment $exp" current_list archive_list
scp current_list archive_list $usrid@alta:/gmao/intranet/research/modeling/agcm/geos5
set rc_commit = $status
endif

echo
echo "Recover Status for Exp: "$exp" = "$rc_recover
echo "Commit  Status for Exp: "$exp" = "$rc_commit
echo

end
